import { useRef, useLayoutEffect } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { ArrowRight } from 'lucide-react';

gsap.registerPlugin(ScrollTrigger);

const communityLooks = [
  { name: 'Soft glam', image: '/images/community_01.jpg', tall: true },
  { name: 'Clean girl', image: '/images/community_02.jpg', tall: false },
  { name: 'Editorial', image: '/images/community_03.jpg', tall: true },
  { name: 'Y2K', image: '/images/community_04.jpg', tall: false },
  { name: 'Night out', image: '/images/community_05.jpg', tall: true },
  { name: 'Glass skin', image: '/images/community_06.jpg', tall: false },
];

export default function CommunitySection() {
  const sectionRef = useRef<HTMLElement>(null);
  const headerRef = useRef<HTMLDivElement>(null);
  const gridRef = useRef<HTMLDivElement>(null);

  useLayoutEffect(() => {
    const section = sectionRef.current;
    const header = headerRef.current;
    const grid = gridRef.current;

    if (!section || !header || !grid) return;

    const ctx = gsap.context(() => {
      // Header animation
      gsap.fromTo(header,
        { x: '-6vw', opacity: 0 },
        {
          x: 0,
          opacity: 1,
          duration: 0.6,
          ease: 'power2.out',
          scrollTrigger: {
            trigger: header,
            start: 'top 80%',
            end: 'top 55%',
            scrub: true
          }
        }
      );

      // Grid cards stagger
      const cards = grid.querySelectorAll('.community-card');
      cards.forEach((card) => {
        gsap.fromTo(card,
          { y: '8vh', opacity: 0, scale: 0.98 },
          {
            y: 0,
            opacity: 1,
            scale: 1,
            duration: 0.5,
            ease: 'power2.out',
            scrollTrigger: {
              trigger: card,
              start: 'top 90%',
              end: 'top 65%',
              scrub: true
            }
          }
        );
      });

    }, section);

    return () => ctx.revert();
  }, []);

  return (
    <section
      ref={sectionRef}
      className="flowing-section bg-[#F6F7F9] z-[60] py-[12vh]"
    >
      <div className="max-w-7xl mx-auto px-6">
        <div className="flex flex-col lg:flex-row gap-12">
          {/* Left Header */}
          <div ref={headerRef} className="lg:w-[30%] lg:sticky lg:top-[20vh] lg:self-start">
            <h2 className="font-display font-bold text-[clamp(32px,4vw,56px)] text-[#111827] mb-4">
              Trending now
            </h2>
            <p className="font-body text-lg text-[#6B7280] mb-8">
              Real looks, generated by the community. Updated daily.
            </p>
            <a 
              href="/community"
              className="inline-flex items-center justify-center px-6 py-3 rounded-full font-medium text-sm transition-all duration-300 border border-[rgba(0,0,0,0.1)] text-[#1F2937] hover:border-[#E11D48] hover:shadow-[0_0_20px_rgba(225,29,72,0.3)] group"
            >
              Explore community
              <ArrowRight className="w-4 h-4 ml-2 transition-transform group-hover:translate-x-1" />
            </a>
          </div>

          {/* Right Grid */}
          <div ref={gridRef} className="lg:w-[70%]">
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
              {communityLooks.map((look, index) => (
                <div
                  key={index}
                  className={`community-card relative rounded-[20px] overflow-hidden card-shadow hover:card-shadow-hover transition-all duration-300 hover:-translate-y-1 group cursor-pointer ${
                    look.tall ? 'row-span-2 h-[400px]' : 'h-[200px]'
                  }`}
                >
                  <img
                    src={look.image}
                    alt={look.name}
                    className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                  />
                  {/* Label */}
                  <div className="absolute bottom-3 left-3">
                    <span className="inline-block px-3 py-1.5 bg-white/90 backdrop-blur-sm rounded-full font-label font-medium text-xs text-[#111827]">
                      {look.name}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
