import type {
  User,
  TokenPackage,
  Style,
  GenerationJob,
  Notification,
  CommunityPost,
  SkinProfile,
  ProgressEntry,
  Product
} from '@/types';

// Mock User
export const mockUser: User = {
  id: 'user-001',
  name: 'Alex',
  email: 'alex@example.com',
  avatar: '',
  tokens: 150,
  tier: 'free',
  totalGenerations: 12,
  createdAt: new Date('2024-01-15'),
};

// Token Packages
export const tokenPackages: TokenPackage[] = [
  {
    id: 'free-trial',
    name: 'Free Trial',
    price: 0,
    tokens: 100,
    bonusTokens: 0,
    features: [
      '100 tokens to start',
      'Standard quality',
      'Watermarked downloads',
      '5 basic styles',
      '10 minute queue'
    ],
  },
  {
    id: 'starter',
    name: 'Starter',
    price: 5000,
    tokens: 500,
    bonusTokens: 0,
    features: [
      '500 tokens',
      'Standard quality',
      'Watermarked downloads',
      'All basic styles',
      '10 minute queue'
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 10000,
    tokens: 1000,
    bonusTokens: 200,
    isPopular: true,
    features: [
      '1,200 tokens (200 bonus)',
      'HD quality',
      'No watermark',
      'All styles',
      'Priority 5 minute queue',
      'Favorites enabled'
    ],
  },
  {
    id: 'elite',
    name: 'Elite',
    price: 25000,
    tokens: 2500,
    bonusTokens: 1000,
    isBestValue: true,
    features: [
      '3,500 tokens (1,000 bonus)',
      '4K quality',
      'No watermark',
      'All styles + early access',
      'Instant 2 minute queue',
      'Unlimited history',
      'Community posting'
    ],
  },
];

// Styles — only includes styles with actual preview images available
// (style_soft_glam, style_clean_girl, style_y2k, style_editorial,
//  style_night_out, style_glass_skin)
export const styles: Style[] = [
  {
    id: 'soft-glam',
    name: 'Soft Glam',
    description: 'Elegant, understated beauty with neutral tones and subtle shimmer. Perfect for everyday sophistication.',
    category: 'soft',
    tokenCost: 10,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/style_soft_glam.jpg',
    isPremium: false,
    tutorial: [
      { step: 1, title: 'Prep your skin', description: 'Start with a clean, moisturized face. Apply primer for smooth application.' },
      { step: 2, title: 'Apply foundation', description: 'Use a light coverage foundation or BB cream for a natural finish.' },
      { step: 3, title: 'Add subtle contour', description: 'Use a cream contour stick for soft definition on cheekbones and jawline.' },
      { step: 4, title: 'Neutral eyeshadow', description: 'Apply warm neutral tones to eyelids and blend softly into the crease.' },
      { step: 5, title: 'Finish with gloss', description: 'Apply a clear or nude lip gloss for a hydrated, natural look.' },
    ],
  },
  {
    id: 'clean-girl',
    name: 'Clean Girl',
    description: 'Minimal makeup, maximum glow. Fresh-faced beauty with dewy skin and brushed-up brows.',
    category: 'soft',
    tokenCost: 10,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/style_clean_girl.jpg',
    isPremium: false,
    tutorial: [
      { step: 1, title: 'Skincare base', description: 'Apply hydrating serum and moisturizer for a dewy base.' },
      { step: 2, title: 'Tinted moisturizer', description: 'Use a sheer tinted moisturizer instead of full coverage foundation.' },
      { step: 3, title: 'Cream blush', description: 'Dab cream blush on cheeks and nose for a natural flush.' },
      { step: 4, title: 'Brow gel', description: 'Brush brows upward with clear gel for a fluffy, natural look.' },
      { step: 5, title: 'Lip balm', description: 'Finish with a tinted lip balm for subtle color and hydration.' },
    ],
  },
  {
    id: 'y2k',
    name: 'Y2K',
    description: 'Playful, nostalgic vibes with shimmery eyeshadows, glossy lips, and fun accents.',
    category: 'y2k',
    tokenCost: 15,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/style_y2k.jpg',
    isPremium: false,
    tutorial: [
      { step: 1, title: 'Glitter primer', description: 'Apply a glitter primer to eyelids for maximum shimmer payoff.' },
      { step: 2, title: 'Shimmery shadows', description: 'Use frosty, iridescent eyeshadows in pastel or silver tones.' },
      { step: 3, title: 'Graphic liner', description: 'Add a thin line of white or colored liner for a playful touch.' },
      { step: 4, title: 'Glossy lips', description: 'Apply a high-shine lip gloss in a light pink or clear shade.' },
      { step: 5, title: 'Face gems optional', description: 'Add small rhinestones near the eyes for extra Y2K flair.' },
    ],
  },
  {
    id: 'editorial',
    name: 'Editorial',
    description: 'High-fashion, avant-garde looks with bold colors and artistic expression.',
    category: 'premium',
    tokenCost: 25,
    qualityTiers: ['hd', '4k'],
    previewImage: '/images/styles/style_editorial.jpg',
    isPremium: true,
    tutorial: [
      { step: 1, title: 'Flawless base', description: 'Create a perfect canvas with full coverage foundation and concealer.' },
      { step: 2, title: 'Bold brows', description: 'Sculpt and define brows with pomade for a strong frame.' },
      { step: 3, title: 'Artistic eyes', description: 'Experiment with bold colors, graphic shapes, or negative space.' },
      { step: 4, title: 'Contour & highlight', description: 'Sculpt cheekbones with dramatic contour and blinding highlight.' },
      { step: 5, title: 'Statement lip', description: 'Choose a bold lip color that complements your eye look.' },
    ],
  },
  {
    id: 'night-out',
    name: 'Night Out',
    description: 'Smoky eyes, bold lips, and glamorous drama for your evening events.',
    category: 'edgy',
    tokenCost: 20,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/style_night_out.jpg',
    isPremium: false,
    tutorial: [
      { step: 1, title: 'Prime lids', description: 'Apply eye primer to ensure your smoky eye stays all night.' },
      { step: 2, title: 'Build smoky eye', description: 'Layer dark eyeshadows, blending from light to dark.' },
      { step: 3, title: 'Winged liner', description: 'Add a dramatic winged eyeliner for extra definition.' },
      { step: 4, title: 'False lashes', description: 'Apply strip lashes or individual lashes for volume.' },
      { step: 5, title: 'Bold lip', description: 'Finish with a deep red or berry lip for classic glamour.' },
    ],
  },
  {
    id: 'glass-skin',
    name: 'Glass Skin',
    description: 'K-beauty inspired ultra-dewy, luminous complexion that looks like porcelain.',
    category: 'soft',
    tokenCost: 15,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/style_glass_skin.jpg',
    isPremium: false,
    tutorial: [
      { step: 1, title: 'Double cleanse', description: 'Start with oil cleanser, then water-based cleanser for clean skin.' },
      { step: 2, title: 'Layer hydration', description: 'Apply multiple layers of hydrating toner or essence.' },
      { step: 3, title: 'Serum & moisturizer', description: 'Use hyaluronic acid serum followed by rich moisturizer.' },
      { step: 4, title: 'Dewy foundation', description: 'Apply a luminous foundation with a damp sponge.' },
      { step: 5, title: 'Liquid highlight', description: 'Dab liquid highlighter on cheekbones, nose, and cupids bow.' },
    ],
  },
];

// Generation Jobs — reuse available demo/portrait images
export const mockGenerationJobs: GenerationJob[] = [
  {
    id: 'job-001',
    userId: 'user-001',
    styleId: 'soft-glam',
    styleName: 'Soft Glam',
    originalImage: '/images/demo_before.jpg',
    resultImage: '/images/demo_after.jpg',
    status: 'completed',
    quality: 'hd',
    tokensUsed: 10,
    createdAt: new Date('2024-12-28'),
    completedAt: new Date('2024-12-28'),
    isFavorite: true,
  },
  {
    id: 'job-002',
    userId: 'user-001',
    styleId: 'clean-girl',
    styleName: 'Clean Girl',
    originalImage: '/images/demo_before.jpg',
    resultImage: '/images/style_clean_girl.jpg',
    status: 'completed',
    quality: 'standard',
    tokensUsed: 10,
    createdAt: new Date('2024-12-27'),
    completedAt: new Date('2024-12-27'),
    isFavorite: false,
  },
  {
    id: 'job-003',
    userId: 'user-001',
    styleId: 'y2k',
    styleName: 'Y2K',
    originalImage: '/images/demo_before.jpg',
    resultImage: '/images/style_y2k.jpg',
    status: 'completed',
    quality: 'hd',
    tokensUsed: 15,
    createdAt: new Date('2024-12-26'),
    completedAt: new Date('2024-12-26'),
    isFavorite: true,
  },
  {
    id: 'job-004',
    userId: 'user-001',
    styleId: 'night-out',
    styleName: 'Night Out',
    originalImage: '/images/demo_before.jpg',
    resultImage: '/images/style_night_out.jpg',
    status: 'completed',
    quality: 'standard',
    tokensUsed: 20,
    createdAt: new Date('2024-12-25'),
    completedAt: new Date('2024-12-25'),
    isFavorite: false,
  },
  {
    id: 'job-005',
    userId: 'user-001',
    styleId: 'glass-skin',
    styleName: 'Glass Skin',
    originalImage: '/images/demo_before.jpg',
    resultImage: '/images/style_glass_skin.jpg',
    status: 'completed',
    quality: 'hd',
    tokensUsed: 15,
    createdAt: new Date('2024-12-24'),
    completedAt: new Date('2024-12-24'),
    isFavorite: false,
  },
  {
    id: 'job-006',
    userId: 'user-001',
    styleId: 'editorial',
    styleName: 'Editorial',
    originalImage: '/images/demo_before.jpg',
    status: 'processing',
    quality: 'hd',
    tokensUsed: 25,
    queuePosition: 3,
    estimatedWaitTime: 8,
    createdAt: new Date('2024-12-29'),
    isFavorite: false,
  },
];

// Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    userId: 'user-001',
    type: 'job_complete',
    title: 'Generation Complete',
    message: 'Your Soft Glam transformation is ready!',
    isRead: false,
    createdAt: new Date('2024-12-28T14:30:00'),
  },
  {
    id: 'notif-002',
    userId: 'user-001',
    type: 'new_style',
    title: 'New Style Available',
    message: 'Try our "Editorial" high-fashion look!',
    isRead: false,
    createdAt: new Date('2024-12-27T10:00:00'),
  },
  {
    id: 'notif-003',
    userId: 'user-001',
    type: 'tip',
    title: 'Glow Up Tip',
    message: 'Good lighting makes better results - face a window!',
    isRead: true,
    createdAt: new Date('2024-12-26T09:00:00'),
  },
  {
    id: 'notif-004',
    userId: 'user-001',
    type: 'low_tokens',
    title: 'Low Token Balance',
    message: 'You have 50 tokens left. Purchase more to keep glowing!',
    isRead: false,
    createdAt: new Date('2024-12-25T16:00:00'),
  },
  {
    id: 'notif-005',
    userId: 'user-001',
    type: 'community',
    title: 'Your Post is Trending',
    message: 'Your Clean Girl look has 50+ upvotes!',
    isRead: true,
    createdAt: new Date('2024-12-24T11:00:00'),
  },
];

// Community Posts — uses 6 actual available community images.
// userAvatar is left empty; the Community page renders a CSS-initial
// fallback when no avatar URL is provided.
export const mockCommunityPosts: CommunityPost[] = [
  {
    id: 'post-001',
    userId: 'user-002',
    userName: 'Sarah M.',
    userAvatar: '',
    styleId: 'soft-glam',
    styleName: 'Soft Glam',
    image: '/images/community/community_01.jpg',
    upvotes: 234,
    hasUpvoted: false,
    createdAt: new Date('2024-12-28'),
  },
  {
    id: 'post-002',
    userId: 'user-003',
    userName: 'Jessica K.',
    userAvatar: '',
    styleId: 'clean-girl',
    styleName: 'Clean Girl',
    image: '/images/community/community_02.jpg',
    upvotes: 189,
    hasUpvoted: true,
    createdAt: new Date('2024-12-27'),
  },
  {
    id: 'post-003',
    userId: 'user-004',
    userName: 'Mina K.',
    userAvatar: '',
    styleId: 'y2k',
    styleName: 'Y2K',
    image: '/images/community/community_03.jpg',
    upvotes: 456,
    hasUpvoted: false,
    createdAt: new Date('2024-12-26'),
  },
  {
    id: 'post-004',
    userId: 'user-005',
    userName: 'Emma L.',
    userAvatar: '',
    styleId: 'night-out',
    styleName: 'Night Out',
    image: '/images/community/community_04.jpg',
    upvotes: 312,
    hasUpvoted: false,
    createdAt: new Date('2024-12-25'),
  },
  {
    id: 'post-005',
    userId: 'user-006',
    userName: 'Priya R.',
    userAvatar: '',
    styleId: 'glass-skin',
    styleName: 'Glass Skin',
    image: '/images/community/community_05.jpg',
    upvotes: 278,
    hasUpvoted: true,
    createdAt: new Date('2024-12-24'),
  },
  {
    id: 'post-006',
    userId: 'user-007',
    userName: 'Chloe T.',
    userAvatar: '',
    styleId: 'editorial',
    styleName: 'Editorial',
    image: '/images/community/community_06.jpg',
    upvotes: 567,
    hasUpvoted: false,
    createdAt: new Date('2024-12-23'),
  },
];

// Skin Profile
export const mockSkinProfile: SkinProfile = {
  userId: 'user-001',
  skinType: 'combination',
  vibe: 'soft',
  goal: 'everyday',
  concerns: ['acne', 'dark circles'],
  inspoImages: [],
  notificationsEnabled: true,
  trackingEnabled: true,
  completionPercentage: 80,
};

// Progress Entries — reuse community/style images since we don't have
// dedicated progress photos
export const mockProgressEntries: ProgressEntry[] = [
  {
    id: 'entry-001',
    userId: 'user-001',
    date: new Date('2024-12-28'),
    photo: '/images/community/community_01.jpg',
    notes: 'Day 30! My skin is glowing so much more now. The routine is really working.',
    mood: 'great',
    glowUpScore: 85,
  },
  {
    id: 'entry-002',
    userId: 'user-001',
    date: new Date('2024-12-21'),
    photo: '/images/community/community_02.jpg',
    notes: 'Week 3 check-in. Noticing less breakouts and more even tone.',
    mood: 'good',
    glowUpScore: 72,
  },
  {
    id: 'entry-003',
    userId: 'user-001',
    date: new Date('2024-12-14'),
    photo: '/images/community/community_03.jpg',
    notes: 'Two weeks in! The hydration is making a big difference.',
    mood: 'good',
    glowUpScore: 65,
  },
  {
    id: 'entry-004',
    userId: 'user-001',
    date: new Date('2024-12-07'),
    photo: '/images/community/community_04.jpg',
    notes: 'First week done. Skin feels softer already.',
    mood: 'okay',
    glowUpScore: 58,
  },
  {
    id: 'entry-005',
    userId: 'user-001',
    date: new Date('2024-12-01'),
    photo: '/images/community/community_05.jpg',
    notes: 'Starting my glow up journey! Taking my first photo.',
    mood: 'good',
    glowUpScore: 50,
  },
];

// Products
export const mockProducts: Product[] = [
  {
    id: 'prod-001',
    name: 'Hydrating Serum',
    brand: 'GlowLab',
    price: 4500,
    image: '/images/styles/style_glass_skin.jpg',
    affiliateLink: '#',
  },
  {
    id: 'prod-002',
    name: 'Matte Foundation',
    brand: 'BeautyBase',
    price: 8500,
    image: '/images/styles/style_soft_glam.jpg',
    affiliateLink: '#',
  },
  {
    id: 'prod-003',
    name: 'Cream Blush',
    brand: 'RosyCheeks',
    price: 3500,
    image: '/images/styles/style_clean_girl.jpg',
    affiliateLink: '#',
  },
  {
    id: 'prod-004',
    name: 'Setting Spray',
    brand: 'StayPut',
    price: 5500,
    image: '/images/styles/style_night_out.jpg',
    affiliateLink: '#',
  },
];

// Tips for Queue Page
export const queueTips = [
  'Tip: Good lighting makes better results',
  'Tip: Face the camera directly',
  'Tip: Remove glasses for best results',
  'Tip: Use a plain background',
  'Tip: Ensure your face is well-lit from the front',
  'Tip: Avoid heavy shadows on your face',
  'Tip: Keep your hair away from your face',
  'Tip: Natural daylight works best',
];

// Hashtag suggestions
export const hashtagSuggestions = [
  '#GlowUp',
  '#GlowHaus',
  '#AIGenerated',
  '#BeautyTransformation',
  '#MakeupIdeas',
  '#BeautyInspo',
  '#BeforeAfter',
  '#AIGlowUp',
  '#VirtualMakeover',
  '#BeautyApp',
];
