import type { 
  User, 
  TokenPackage, 
  Style, 
  GenerationJob, 
  Notification, 
  CommunityPost,
  SkinProfile,
  ProgressEntry,
  Product
} from '@/types';

// Mock User
export const mockUser: User = {
  id: 'user-001',
  name: 'Alex',
  email: 'alex@example.com',
  avatar: '/images/avatars/alex.jpg',
  tokens: 150,
  tier: 'free',
  totalGenerations: 12,
  createdAt: new Date('2024-01-15'),
};

// Token Packages
export const tokenPackages: TokenPackage[] = [
  {
    id: 'free-trial',
    name: 'Free Trial',
    price: 0,
    tokens: 100,
    bonusTokens: 0,
    features: [
      '100 tokens to start',
      'Standard quality',
      'Watermarked downloads',
      '5 basic styles',
      '10 minute queue'
    ],
  },
  {
    id: 'starter',
    name: 'Starter',
    price: 5000,
    tokens: 500,
    bonusTokens: 0,
    features: [
      '500 tokens',
      'Standard quality',
      'Watermarked downloads',
      'All basic styles',
      '10 minute queue'
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 10000,
    tokens: 1000,
    bonusTokens: 200,
    isPopular: true,
    features: [
      '1,200 tokens (200 bonus)',
      'HD quality',
      'No watermark',
      'All styles',
      'Priority 5 minute queue',
      'Favorites enabled'
    ],
  },
  {
    id: 'elite',
    name: 'Elite',
    price: 25000,
    tokens: 2500,
    bonusTokens: 1000,
    isBestValue: true,
    features: [
      '3,500 tokens (1,000 bonus)',
      '4K quality',
      'No watermark',
      'All styles + early access',
      'Instant 2 minute queue',
      'Unlimited history',
      'Community posting'
    ],
  },
];

// Styles
export const styles: Style[] = [
  {
    id: 'soft-glam',
    name: 'Soft Glam',
    description: 'Elegant, understated beauty with neutral tones and subtle shimmer. Perfect for everyday sophistication.',
    category: 'soft',
    tokenCost: 10,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/soft-glam.jpg',
    isPremium: false,
    tutorial: [
      { step: 1, title: 'Prep your skin', description: 'Start with a clean, moisturized face. Apply primer for smooth application.' },
      { step: 2, title: 'Apply foundation', description: 'Use a light coverage foundation or BB cream for a natural finish.' },
      { step: 3, title: 'Add subtle contour', description: 'Use a cream contour stick for soft definition on cheekbones and jawline.' },
      { step: 4, title: 'Neutral eyeshadow', description: 'Apply warm neutral tones to eyelids and blend softly into the crease.' },
      { step: 5, title: 'Finish with gloss', description: 'Apply a clear or nude lip gloss for a hydrated, natural look.' },
    ],
  },
  {
    id: 'clean-girl',
    name: 'Clean Girl',
    description: 'Minimal makeup, maximum glow. Fresh-faced beauty with dewy skin and brushed-up brows.',
    category: 'soft',
    tokenCost: 10,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/clean-girl.jpg',
    isPremium: false,
    tutorial: [
      { step: 1, title: 'Skincare base', description: 'Apply hydrating serum and moisturizer for a dewy base.' },
      { step: 2, title: 'Tinted moisturizer', description: 'Use a sheer tinted moisturizer instead of full coverage foundation.' },
      { step: 3, title: 'Cream blush', description: 'Dab cream blush on cheeks and nose for a natural flush.' },
      { step: 4, title: 'Brow gel', description: 'Brush brows upward with clear gel for a fluffy, natural look.' },
      { step: 5, title: 'Lip balm', description: 'Finish with a tinted lip balm for subtle color and hydration.' },
    ],
  },
  {
    id: 'y2k',
    name: 'Y2K',
    description: 'Playful, nostalgic vibes with shimmery eyeshadows, glossy lips, and fun accents.',
    category: 'y2k',
    tokenCost: 15,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/y2k.jpg',
    isPremium: false,
    tutorial: [
      { step: 1, title: 'Glitter primer', description: 'Apply a glitter primer to eyelids for maximum shimmer payoff.' },
      { step: 2, title: 'Shimmery shadows', description: 'Use frosty, iridescent eyeshadows in pastel or silver tones.' },
      { step: 3, title: 'Graphic liner', description: 'Add a thin line of white or colored liner for a playful touch.' },
      { step: 4, title: 'Glossy lips', description: 'Apply a high-shine lip gloss in a light pink or clear shade.' },
      { step: 5, title: 'Face gems optional', description: 'Add small rhinestones near the eyes for extra Y2K flair.' },
    ],
  },
  {
    id: 'editorial',
    name: 'Editorial',
    description: 'High-fashion, avant-garde looks with bold colors and artistic expression.',
    category: 'premium',
    tokenCost: 25,
    qualityTiers: ['hd', '4k'],
    previewImage: '/images/styles/editorial.jpg',
    isPremium: true,
    tutorial: [
      { step: 1, title: 'Flawless base', description: 'Create a perfect canvas with full coverage foundation and concealer.' },
      { step: 2, title: 'Bold brows', description: 'Sculpt and define brows with pomade for a strong frame.' },
      { step: 3, title: 'Artistic eyes', description: 'Experiment with bold colors, graphic shapes, or negative space.' },
      { step: 4, title: 'Contour & highlight', description: 'Sculpt cheekbones with dramatic contour and blinding highlight.' },
      { step: 5, title: 'Statement lip', description: 'Choose a bold lip color that complements your eye look.' },
    ],
  },
  {
    id: 'night-out',
    name: 'Night Out',
    description: 'Smoky eyes, bold lips, and glamorous drama for your evening events.',
    category: 'edgy',
    tokenCost: 20,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/night-out.jpg',
    isPremium: false,
    tutorial: [
      { step: 1, title: 'Prime lids', description: 'Apply eye primer to ensure your smoky eye stays all night.' },
      { step: 2, title: 'Build smoky eye', description: 'Layer dark eyeshadows, blending from light to dark.' },
      { step: 3, title: 'Winged liner', description: 'Add a dramatic winged eyeliner for extra definition.' },
      { step: 4, title: 'False lashes', description: 'Apply strip lashes or individual lashes for volume.' },
      { step: 5, title: 'Bold lip', description: 'Finish with a deep red or berry lip for classic glamour.' },
    ],
  },
  {
    id: 'glass-skin',
    name: 'Glass Skin',
    description: 'K-beauty inspired ultra-dewy, luminous complexion that looks like porcelain.',
    category: 'soft',
    tokenCost: 15,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/glass-skin.jpg',
    isPremium: false,
    tutorial: [
      { step: 1, title: 'Double cleanse', description: 'Start with oil cleanser, then water-based cleanser for clean skin.' },
      { step: 2, title: 'Layer hydration', description: 'Apply multiple layers of hydrating toner or essence.' },
      { step: 3, title: 'Serum & moisturizer', description: 'Use hyaluronic acid serum followed by rich moisturizer.' },
      { step: 4, title: 'Dewy foundation', description: 'Apply a luminous foundation with a damp sponge.' },
      { step: 5, title: 'Liquid highlight', description: 'Dab liquid highlighter on cheekbones, nose, and cupids bow.' },
    ],
  },
  {
    id: 'grunge',
    name: 'Grunge',
    description: 'Edgy, lived-in makeup with smudged liner and matte textures.',
    category: 'edgy',
    tokenCost: 20,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/grunge.jpg',
    isPremium: false,
  },
  {
    id: 'classic-red',
    name: 'Classic Red',
    description: 'Timeless elegance with a bold red lip and defined eyes.',
    category: 'classic',
    tokenCost: 15,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/classic-red.jpg',
    isPremium: false,
  },
  {
    id: 'bronze-goddess',
    name: 'Bronze Goddess',
    description: 'Sun-kissed glow with warm bronzy tones and golden highlights.',
    category: 'trending',
    tokenCost: 20,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/bronze-goddess.jpg',
    isPremium: false,
  },
  {
    id: 'futuristic',
    name: 'Futuristic',
    description: 'Cyber-inspired looks with metallics, neons, and holographic accents.',
    category: 'new',
    tokenCost: 30,
    qualityTiers: ['hd', '4k'],
    previewImage: '/images/styles/futuristic.jpg',
    isPremium: true,
  },
  {
    id: 'vintage-glam',
    name: 'Vintage Glam',
    description: 'Old Hollywood sophistication with defined creases and matte red lips.',
    category: 'classic',
    tokenCost: 20,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/vintage-glam.jpg',
    isPremium: false,
  },
  {
    id: 'e-girl',
    name: 'E-Girl',
    description: 'Internet-inspired with bold blush, winged liner, and playful details.',
    category: 'y2k',
    tokenCost: 15,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/e-girl.jpg',
    isPremium: false,
  },
  {
    id: 'natural-no-makeup',
    name: 'No Makeup',
    description: 'The ultimate natural look - enhance without looking made up.',
    category: 'soft',
    tokenCost: 10,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/no-makeup.jpg',
    isPremium: false,
  },
  {
    id: 'glitter-glam',
    name: 'Glitter Glam',
    description: 'All-out sparkle and shine for special occasions.',
    category: 'premium',
    tokenCost: 25,
    qualityTiers: ['hd', '4k'],
    previewImage: '/images/styles/glitter-glam.jpg',
    isPremium: true,
  },
  {
    id: 'monochromatic',
    name: 'Monochromatic',
    description: 'One color family for eyes, cheeks, and lips in harmonious tones.',
    category: 'trending',
    tokenCost: 15,
    qualityTiers: ['standard', 'hd', '4k'],
    previewImage: '/images/styles/monochromatic.jpg',
    isPremium: false,
  },
];

// Generation Jobs
export const mockGenerationJobs: GenerationJob[] = [
  {
    id: 'job-001',
    userId: 'user-001',
    styleId: 'soft-glam',
    styleName: 'Soft Glam',
    originalImage: '/images/generations/original-1.jpg',
    resultImage: '/images/generations/result-1.jpg',
    status: 'completed',
    quality: 'hd',
    tokensUsed: 10,
    createdAt: new Date('2024-12-28'),
    completedAt: new Date('2024-12-28'),
    isFavorite: true,
  },
  {
    id: 'job-002',
    userId: 'user-001',
    styleId: 'clean-girl',
    styleName: 'Clean Girl',
    originalImage: '/images/generations/original-2.jpg',
    resultImage: '/images/generations/result-2.jpg',
    status: 'completed',
    quality: 'standard',
    tokensUsed: 10,
    createdAt: new Date('2024-12-27'),
    completedAt: new Date('2024-12-27'),
    isFavorite: false,
  },
  {
    id: 'job-003',
    userId: 'user-001',
    styleId: 'y2k',
    styleName: 'Y2K',
    originalImage: '/images/generations/original-3.jpg',
    resultImage: '/images/generations/result-3.jpg',
    status: 'completed',
    quality: 'hd',
    tokensUsed: 15,
    createdAt: new Date('2024-12-26'),
    completedAt: new Date('2024-12-26'),
    isFavorite: true,
  },
  {
    id: 'job-004',
    userId: 'user-001',
    styleId: 'night-out',
    styleName: 'Night Out',
    originalImage: '/images/generations/original-4.jpg',
    resultImage: '/images/generations/result-4.jpg',
    status: 'completed',
    quality: 'standard',
    tokensUsed: 20,
    createdAt: new Date('2024-12-25'),
    completedAt: new Date('2024-12-25'),
    isFavorite: false,
  },
  {
    id: 'job-005',
    userId: 'user-001',
    styleId: 'glass-skin',
    styleName: 'Glass Skin',
    originalImage: '/images/generations/original-5.jpg',
    resultImage: '/images/generations/result-5.jpg',
    status: 'completed',
    quality: 'hd',
    tokensUsed: 15,
    createdAt: new Date('2024-12-24'),
    completedAt: new Date('2024-12-24'),
    isFavorite: false,
  },
  {
    id: 'job-006',
    userId: 'user-001',
    styleId: 'editorial',
    styleName: 'Editorial',
    originalImage: '/images/generations/original-6.jpg',
    status: 'processing',
    quality: 'hd',
    tokensUsed: 25,
    queuePosition: 3,
    estimatedWaitTime: 8,
    createdAt: new Date('2024-12-29'),
    isFavorite: false,
  },
];

// Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    userId: 'user-001',
    type: 'job_complete',
    title: 'Generation Complete',
    message: 'Your Soft Glam transformation is ready!',
    isRead: false,
    createdAt: new Date('2024-12-28T14:30:00'),
  },
  {
    id: 'notif-002',
    userId: 'user-001',
    type: 'new_style',
    title: 'New Style Available',
    message: 'Try our new "Futuristic" cyber-inspired look!',
    isRead: false,
    createdAt: new Date('2024-12-27T10:00:00'),
  },
  {
    id: 'notif-003',
    userId: 'user-001',
    type: 'tip',
    title: 'Glow Up Tip',
    message: 'Good lighting makes better results - face a window!',
    isRead: true,
    createdAt: new Date('2024-12-26T09:00:00'),
  },
  {
    id: 'notif-004',
    userId: 'user-001',
    type: 'low_tokens',
    title: 'Low Token Balance',
    message: 'You have 50 tokens left. Purchase more to keep glowing!',
    isRead: false,
    createdAt: new Date('2024-12-25T16:00:00'),
  },
  {
    id: 'notif-005',
    userId: 'user-001',
    type: 'community',
    title: 'Your Post is Trending',
    message: 'Your Clean Girl look has 50+ upvotes!',
    isRead: true,
    createdAt: new Date('2024-12-24T11:00:00'),
  },
];

// Community Posts
export const mockCommunityPosts: CommunityPost[] = [
  {
    id: 'post-001',
    userId: 'user-002',
    userName: 'Sarah M.',
    userAvatar: '/images/avatars/sarah.jpg',
    styleId: 'soft-glam',
    styleName: 'Soft Glam',
    image: '/images/community/post-1.jpg',
    upvotes: 234,
    hasUpvoted: false,
    createdAt: new Date('2024-12-28'),
  },
  {
    id: 'post-002',
    userId: 'user-003',
    userName: 'Jessica K.',
    userAvatar: '/images/avatars/jessica.jpg',
    styleId: 'clean-girl',
    styleName: 'Clean Girl',
    image: '/images/community/post-2.jpg',
    upvotes: 189,
    hasUpvoted: true,
    createdAt: new Date('2024-12-27'),
  },
  {
    id: 'post-003',
    userId: 'user-004',
    userName: 'Mina K.',
    userAvatar: '/images/avatars/mina.jpg',
    styleId: 'y2k',
    styleName: 'Y2K',
    image: '/images/community/post-3.jpg',
    upvotes: 456,
    hasUpvoted: false,
    createdAt: new Date('2024-12-26'),
  },
  {
    id: 'post-004',
    userId: 'user-005',
    userName: 'Emma L.',
    userAvatar: '/images/avatars/emma.jpg',
    styleId: 'night-out',
    styleName: 'Night Out',
    image: '/images/community/post-4.jpg',
    upvotes: 312,
    hasUpvoted: false,
    createdAt: new Date('2024-12-25'),
  },
  {
    id: 'post-005',
    userId: 'user-006',
    userName: 'Priya R.',
    userAvatar: '/images/avatars/priya.jpg',
    styleId: 'glass-skin',
    styleName: 'Glass Skin',
    image: '/images/community/post-5.jpg',
    upvotes: 278,
    hasUpvoted: true,
    createdAt: new Date('2024-12-24'),
  },
  {
    id: 'post-006',
    userId: 'user-007',
    userName: 'Chloe T.',
    userAvatar: '/images/avatars/chloe.jpg',
    styleId: 'editorial',
    styleName: 'Editorial',
    image: '/images/community/post-6.jpg',
    upvotes: 567,
    hasUpvoted: false,
    createdAt: new Date('2024-12-23'),
  },
  {
    id: 'post-007',
    userId: 'user-008',
    userName: 'Zoe W.',
    userAvatar: '/images/avatars/zoe.jpg',
    styleId: 'grunge',
    styleName: 'Grunge',
    image: '/images/community/post-7.jpg',
    upvotes: 145,
    hasUpvoted: false,
    createdAt: new Date('2024-12-22'),
  },
  {
    id: 'post-008',
    userId: 'user-009',
    userName: 'Luna P.',
    userAvatar: '/images/avatars/luna.jpg',
    styleId: 'bronze-goddess',
    styleName: 'Bronze Goddess',
    image: '/images/community/post-8.jpg',
    upvotes: 389,
    hasUpvoted: true,
    createdAt: new Date('2024-12-21'),
  },
];

// Skin Profile
export const mockSkinProfile: SkinProfile = {
  userId: 'user-001',
  skinType: 'combination',
  vibe: 'soft',
  goal: 'everyday',
  concerns: ['acne', 'dark circles'],
  inspoImages: ['/images/inspo/1.jpg', '/images/inspo/2.jpg', '/images/inspo/3.jpg'],
  notificationsEnabled: true,
  completionPercentage: 80,
};

// Progress Entries
export const mockProgressEntries: ProgressEntry[] = [
  {
    id: 'entry-001',
    userId: 'user-001',
    date: new Date('2024-12-28'),
    photo: '/images/progress/day-30.jpg',
    notes: 'Day 30! My skin is glowing so much more now. The routine is really working.',
    mood: 'great',
    glowUpScore: 85,
  },
  {
    id: 'entry-002',
    userId: 'user-001',
    date: new Date('2024-12-21'),
    photo: '/images/progress/day-23.jpg',
    notes: 'Week 3 check-in. Noticing less breakouts and more even tone.',
    mood: 'good',
    glowUpScore: 72,
  },
  {
    id: 'entry-003',
    userId: 'user-001',
    date: new Date('2024-12-14'),
    photo: '/images/progress/day-16.jpg',
    notes: 'Two weeks in! The hydration is making a big difference.',
    mood: 'good',
    glowUpScore: 65,
  },
  {
    id: 'entry-004',
    userId: 'user-001',
    date: new Date('2024-12-07'),
    photo: '/images/progress/day-9.jpg',
    notes: 'First week done. Skin feels softer already.',
    mood: 'okay',
    glowUpScore: 58,
  },
  {
    id: 'entry-005',
    userId: 'user-001',
    date: new Date('2024-12-01'),
    photo: '/images/progress/day-1.jpg',
    notes: 'Starting my glow up journey! Taking my first photo.',
    mood: 'good',
    glowUpScore: 50,
  },
];

// Products
export const mockProducts: Product[] = [
  {
    id: 'prod-001',
    name: 'Hydrating Serum',
    brand: 'GlowLab',
    price: 4500,
    image: '/images/products/serum.jpg',
    affiliateLink: '#',
  },
  {
    id: 'prod-002',
    name: 'Matte Foundation',
    brand: 'BeautyBase',
    price: 8500,
    image: '/images/products/foundation.jpg',
    affiliateLink: '#',
  },
  {
    id: 'prod-003',
    name: 'Cream Blush',
    brand: 'RosyCheeks',
    price: 3500,
    image: '/images/products/blush.jpg',
    affiliateLink: '#',
  },
  {
    id: 'prod-004',
    name: 'Setting Spray',
    brand: 'StayPut',
    price: 5500,
    image: '/images/products/spray.jpg',
    affiliateLink: '#',
  },
];

// Tips for Queue Page
export const queueTips = [
  'Tip: Good lighting makes better results',
  'Tip: Face the camera directly',
  'Tip: Remove glasses for best results',
  'Tip: Use a plain background',
  'Tip: Ensure your face is well-lit from the front',
  'Tip: Avoid heavy shadows on your face',
  'Tip: Keep your hair away from your face',
  'Tip: Natural daylight works best',
];

// Hashtag suggestions
export const hashtagSuggestions = [
  '#GlowUp',
  '#GlowHaus',
  '#AIGenerated',
  '#BeautyTransformation',
  '#MakeupIdeas',
  '#BeautyInspo',
  '#BeforeAfter',
  '#AIGlowUp',
  '#VirtualMakeover',
  '#BeautyApp',
];
